Web3/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Web3.Models
{
    public class Item
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public decimal Price { get; set; }

        [MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(16)]
        public string Code { get; set; }

        [MaxLength(10)]
        public string CategoryCode { get; set; }

        public int? CatalogId { get; set; }
        [ForeignKey("CatalogId")]
        public virtual Catalog Catalog { get; set; }

        public virtual IList<SubOrder> SubOrders { get; set; }

        public Item()
        {
            SubOrders = new List<SubOrder>();
        }
    }
}

Web3/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web3.DL;
using Web3.DOL;

namespace Web3.Controllers
{
    public class CartController : Controller
    {
        public ActionResult Index()
        {
            var model = new List<ItemCategoryDetails>();

            if (TempData["CartHasItems"] != null)
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];
                model = currentCart.GetItemsByCategory();
            }

            ViewBag.TotalAmount = model.Sum(x => x.TotalPrice);

            return View(model);
        }

        public JsonResult AddEntityToCart(int itemId, int qty)
        {
            int differentItemsInCart = -1;

            if (TempData["CartHasItems"] == null)
            {
                Cart cart = new Cart();
                cart.EntityList.Add(new CartEntity()
                {
                    ItemId = itemId,
                    Qty = qty
                });

                TempData["CartHasItems"] = true;
                TempData["CurrentCart"] = cart;

                differentItemsInCart = cart.EntityList.Count();
            }
            else
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];

                int index = currentCart.EntityList.FindIndex(x => x.ItemId == itemId);
                if (index >= 0)
                {
                    currentCart.EntityList[index].Qty += qty;
                }
                else
                {
                    currentCart.EntityList.Add(new CartEntity
                    {
                        ItemId = itemId,
                        Qty = qty
                    });
                }

                TempData["CurrentCart"] = currentCart;
                TempData["CartHasItems"] = true;

                differentItemsInCart = currentCart.EntityList.Count();
            }

            return Json(differentItemsInCart);
        }

        public JsonResult CheckCartState()
        {
            if (TempData["CurrentCart"] != null)
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];
                int differentItemsInCart = currentCart.EntityList.Count();
                return Json(differentItemsInCart);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult SaveCart(List<CartEntity> items)
        {
            try
            {
                Cart newCart = new Cart();
                foreach (var item in items)
                {
                    if (item.Qty > 0)
                    {
                        newCart.EntityList.Add(new CartEntity
                        {
                            ItemId = item.ItemId,
                            Qty = item.Qty
                        });
                    }
                }

                TempData["CurrentCart"] = newCart;
                TempData["CartHasItems"] = true;
            }
            catch (Exception ex)
            {
                return Json(new { success = false });
            }

            return Json(new { success = true });
        }

        public PartialViewResult AnalyzeCart()
        {
            if (TempData["CartHasItems"] != null)
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];

                List<int> itemIds = currentCart.EntityList.Select(x => x.ItemId).ToList();
                List<BestItemOffer> bestOffers = BestItemOffer.MapToBests(itemIds);

                return PartialView("_AnalyzedCartPartial", bestOffers);
            }

            return null;
        }

        public JsonResult ConvertItem(BestItemOffer conversionItem)
        {
            if (TempData["CartHasItems"] != null)
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];
                var index = currentCart.EntityList.FindIndex(x => x.ItemId == conversionItem.ItemId);

                if (index >= 0)
                    currentCart.EntityList[index].ItemId = conversionItem.BestItemId;

                TempData["CurrentCart"] = currentCart;

                var replacement = ItemDetails.GetRelacement(conversionItem.BestItemId);

                return Json(new { oldId = conversionItem.ItemId, replacement, success = true });
            }

            return Json(new { success = false });
        }

    }
}

Web3/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web3.DL;
using Web3.DTO;
using Web3.Helpers;
using Web3.Helpers.Filters;

namespace Web3.Controllers
{
    public class CatalogController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCatalogData(DataTableFilter dtFilter, CatalogFilter filter)
        {
            var data = DTOCatalog.MapToDTO(new CatalogRepository().GetData(dtFilter, filter));

            return Json(new {
                recordsTotal = data.Count,
                recordsFiltered = data.Count,
                data = data.Data
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCatalog(int id)
        {
            var data = DTOCatalog.MapToDTO(new CatalogRepository().GetIndividual(id));

            return Json(data);
        }
    }
}

Web3/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web3.DL;
using Web3.DTO;
using Web3.Helpers;
using Web3.Helpers.Filters;

namespace Web3.Controllers
{
    public class ItemController : Controller
    {
        public JsonResult GetItemData(DataTableFilter dtFilter, ItemFilter filter)
        {
            var data = DTOItem.MapToDTO(new ItemRepository().GetData(dtFilter, filter));

            return Json(new
            {
                recordsTotal = data.Count,
                recordsFiltered = data.Count,
                data = data.Data
            }, JsonRequestBehavior.AllowGet);

        }
    }
}

Web3/Views/Item/TablePartial.cshtml
@model  Web3.Helpers.RowClickHandler.ItemClickHandlers

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-sm-6">
                <h4>
                    Items for catalog
                </h4>
            </div>
            <div class="col-sm-6">
                <h5 class="pull-right" id="itemsCatalogName" style="font-style: italic; color: slategray"></h5>
            </div>
        </div>
    </div>

    <div class="panel-body">
        <table id="itemTable" class="display">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Code</th>
                    <td>Category Code</td>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

</div>

<script>
    var selfCatalogId = null;
    var rowClickHandlerId = '@Model';

    var addItemToCart = function (itemId, qty) {
        $.ajax({
            url: '@Url.Action("AddEntityToCart", "Cart")',
            dataType: 'json',
            type: 'POST',
            data: {
                itemId, 
                qty
            },
            success: function (data) {
                if (data >= 0) {
                    $.notify("Successfully added to cart.", "success");
                    $('#cartNumber').text(data);
                }
                else {
                    $.notify("Error in adding to cart.", "error");
                }
            }
        });
    };

    var openModalRowClickHandler = function (itemId) {
        var dialog = bootbox.dialog({
            title: 'Enter item quantity',
            message: `<div class="form-group">
                <label for= "email" > Item quantity</label>
                <input type="number" class="form-control" id="itemQtyModalId" name="qty" placeholder="Enter quantity"></input>
                </div >`,
            closeButton: true,
            buttons: [
                {
                    label: "Save",
                    className: "btn btn-primary pull-rigth",
                    callback: function () {
                        var qty = $('#itemQtyModalId').val();
                        addItemToCart(itemId, qty);
                    }
                },
                {
                    label: "Close",
                    className: "btn btn-default pull-right",
                    callback: function () {
                    }
                }
            ],
        });
    };

    var rowClickHandler = function (rowId) {
        if (rowClickHandlerId == 'ModalOpening')
            openModalRowClickHandler(rowId);
    };

    var updateItemsCatalogName = function (catalogName) {
        $('#itemsCatalogName').text(catalogName);
    };

    $(document).ready(function () {

        var collectItemFilter = function () {
            return {
                CatalogId: selfCatalogId
            };
        };

        var itemTable = $('#itemTable').DataTable({
                lengthChange: true,
                autoWidth: false,
                processing: true,
                serverSide: true,
                searching: true,
                ordering: true,
                paging: true,
                fixedColumns: true,
                fixedHeader: true,
                scrollX: true,
                scrollY: "700px",
                scrollCollapse: true,
                info: true,
                pageLength: 10,
                lengthMenu: [5, 10, 25, 50, 100, 250, 500],
                pagingType: "first_last_numbers",
                createdRow: function (row, data, dataIndex) {
                    $(row).attr('data-id', data.Id);
                },
                ajax: {
                    url: '@Url.Action("GetItemData", "Item")',
                    data: function (request) {
                        var filtering = collectItemFilter();
                        return {
                            dtFilter: request,
                            filter: filtering
                        };
                    },
                    type: "POST",
                    dataSrc: 'data'
                },
                language: {
                    processing: ''
                },
                drawCallback: function (settings) {
                    $('.table-overlay').hide();
                },
                columns: [{
                    data: "Name",
                    orderable: true,
                    render: function (data, type, full, meta) {
                        return "<span class='datacell'>" + (full.Name) + "</span>";
                    }
                }, {
                    data: "Price",
                    orderable: true,
                    className: "text-left",
                        render: function (data, type, full, meta) {
                            return "<span class='datacell'>" + (full.Price) + "</span>";
                    }
                }, {
                    data: "Code",
                    orderable: true,
                    className: "text-left",
                        render: function (data, type, full, meta) {
                            return "<span class='datacell'>" + (full.Code) + "</span>";
                    }
                }, {
                    data: "Category Code",
                    orderable: false,
                        render: function (data, type, full, meta) {
                        return "<span class='datacell'>" + (full.CategoryCode) + "</span>";
                    }
                }]
        });

    });

    var drawItemTableForCatalog = function (catalogId) {
        $("#itemTableDiv").css("display", "block");
        selfCatalogId = catalogId;
        changeCatalogHeader(catalogId);
        $('#itemTable').DataTable().ajax.reload();
    };

    var changeCatalogHeader = function (catalogId) {
        $.ajax({
            url: '@Url.Action("GetCatalog", "Catalog")',
            dataType: 'json',
            type: 'POST',
            data: {
                id: catalogId
            },
            success: function (data) {
                updateItemsCatalogName(data.Code);
            }
        });
    };

    $('#itemTable tbody').on('click', 'tr', function () {
        var itemId = $(this).data("id");
        rowClickHandler(itemId);
    });

</script>