Web3/Controllers/AnalyticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web3.DOL;
using Web3.Helpers.HighChart;

namespace Web3.Controllers
{
    public class AnalyticsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetMonthlyCosts(DateTime? filterDate, string period)
        {
            HighChartData data = null;
            List<string> cat = null;

            if (period.Equals("year"))
            {
                data = new MonthlyCostByCategory().GetForYear(filterDate.HasValue ? filterDate.Value.Year : DateTime.Now.Year);
                cat = new List<string> { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
            }
            else if(period.Equals("month"))
            {
                data = new MonthlyCostByCategory().GetForMonth(filterDate);
                cat = GenerateListForMonth(filterDate);
            }

            return Json(new { data , cat});
        }

        private List<string> GenerateListForMonth(DateTime? date)
        {
            List<string> cat = new List<string>();

            var month = date.HasValue ? date.Value.Month : DateTime.Now.Month;
            var year = date.HasValue ? date.Value.Year : DateTime.Now.Year;
    
            if(month == 1 || month == 3 || month == 5 || month == 7 || month == 8 || month == 10 || month == 12)
            {
                for (int i = 1; i <= 31; i++)
                    cat.Add(i.ToString());
            }
            else if(month == 4 || month == 6 || month == 9 || month == 11)
            {
                for (int i = 1; i <= 30; i++)
                    cat.Add(i.ToString());
            }
            else if(year % 4 == 0)
            {
                for (int i = 1; i <= 29; i++)
                    cat.Add(i.ToString());
            }
            else
            {
                for (int i = 1; i <= 28; i++)
                    cat.Add(i.ToString());
            }

            return cat;
        }
    }
}

Web3/Views/Analytics/Index.cshtml
<br />

<div class="panel panel-default">
    <div class="panel-heading" data-toggle="collapse" data-target="#bottomPartMonFil">
        <h4>
            Filters
        </h4>
    </div>

    <div id="bottomPartMonFil" class="collapse">
        <div class="panel-body">

            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-1">
                    <label>Period</label>
                </div>
                <div class="col-sm-4">
                    <select class="form-control periodFilter" name="period" style="width: 250px">
                        <option value="year">Year</option>
                        <option value="month">Month</option>
                    </select>
                </div>

                <div class='col-sm-2'>
                    <label>Begining Date To:</label>
                </div>

                <div class='col-sm-3'>
                    <div class="form-group">
                        <div class='input-group date' id='filterDate'>
                            <input type='text' class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <button class="applyFilterBtn btn btn-secondary pull-right" style="margin-right: 50px;">Apply</button>
            </div>

        </div>
    </div>
</div>

<div class="panel-default">
    <div class="panel-heading" data-toggle="collapse" data-target="#bottomPartMon">
        <h4>Monthly Costs</h4>
    </div>

    <div id="bottomPartMon" class="collapse show">
        <div class="panel-body">
            <div id="monthlytChart">
            </div>
        </div>
    </div>

</div>


<script>
    var costChart;
    var year = 2019;
    var month = 10;
    var period = "year";

    function requestData() {
        $('#bottomPartMon').block({ message: "Loading chart..." });
        debugger;
        period = $('.periodFilter').val();
        var dateFromFilter = new Date($('#filterDate').find("input").val());
        filterDate = dateFromFilter != 'Invalid Date' ? dateFromFilter.toISOString() : null;

        $.ajax({
            url: '@Url.Action("GetMonthlyCosts","Analytics")',
            type: "POST",
            data: { filterDate, period},
            success: function (result) {
                debugger;
                var seriesLength = costChart.series.length;
                for (var i = seriesLength - 1; i > -1; i--) {
                    costChart.series[i].remove();
                }
                costChart.xAxis[0].setCategories(result.cat);

                for (var i = 0; i < result.data.Series.length; i++) {
                    costChart.addSeries({
                        name: result.data.Series[i].Name, 
                        data: result.data.Series[i].Data
                    }, false);
                }
                costChart.redraw();

                $('#bottomPartMon').unblock();
            },
            cache: false
        });
    };

    $(document).ready(function () {
        $('.periodFilter').select2();

        $('#filterDate').datetimepicker({
            locale: 'ru'
        });

        $('.applyFilterBtn').click(function () {
            debugger;
            requestData();
        });

        costChart = Highcharts.chart('monthlytChart', {
            chart: {
                type: 'line',
                events: {
                    load: requestData
                }
            },
            title: {
                text: 'Monthly Costs'
            },
            subtitle: {
                text: ''
            },
            xAxis: {
                //categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            },
            yAxis: {
                title: {
                    text: 'Cost ($)'
                }
            },
            series: []
        });
    });
</script>