Web3/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web3.DL;
using Web3.DOL;

namespace Web3.Controllers
{
    public class CartController : Controller
    {
        public ActionResult Index()
        {
            var model = new List<ItemCategoryDetails>();

            if (TempData["CartHasItems"] != null)
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];
                model = currentCart.GetItemsByCategory();
            }

            ViewBag.TotalAmount = model.Sum(x => x.TotalPrice);

            return View(model);
        }

        public JsonResult AddEntityToCart(int itemId, int qty)
        {
            int differentItemsInCart = -1;

            if (TempData["CartHasItems"] == null)
            {
                Cart cart = new Cart();
                cart.EntityList.Add(new CartEntity()
                {
                    ItemId = itemId,
                    Qty = qty
                });

                TempData["CartHasItems"] = true;
                TempData["CurrentCart"] = cart;

                differentItemsInCart = cart.EntityList.Count();
            }
            else
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];

                int index = currentCart.EntityList.FindIndex(x => x.ItemId == itemId);
                if (index >= 0)
                {
                    currentCart.EntityList[index].Qty += qty;
                }
                else
                {
                    currentCart.EntityList.Add(new CartEntity
                    {
                        ItemId = itemId,
                        Qty = qty
                    });
                }

                TempData["CurrentCart"] = currentCart;
                TempData["CartHasItems"] = true;

                differentItemsInCart = currentCart.EntityList.Count();
            }

            return Json(differentItemsInCart);
        }

        public JsonResult CheckCartState()
        {
            if (TempData["CurrentCart"] != null)
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];
                int differentItemsInCart = currentCart.EntityList.Count();
                return Json(differentItemsInCart);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult SaveCart(List<CartEntity> items)
        {
            try
            {
                Cart newCart = new Cart();
                foreach (var item in items)
                {
                    if (item.Qty > 0)
                    {
                        newCart.EntityList.Add(new CartEntity
                        {
                            ItemId = item.ItemId,
                            Qty = item.Qty
                        });
                    }
                }

                TempData["CurrentCart"] = newCart;
                TempData["CartHasItems"] = true;
            }
            catch (Exception ex)
            {
                return Json(new { success = false });
            }

            return Json(new { success = true });
        }

        public PartialViewResult AnalyzeCart()
        {
            if (TempData["CartHasItems"] != null)
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];

                List<int> itemIds = currentCart.EntityList.Select(x => x.ItemId).ToList();
                List<BestItemOffer> bestOffers = BestItemOffer.MapToBests(itemIds);

                return PartialView("_AnalyzedCartPartial", bestOffers);
            }

            return null;
        }

        public JsonResult ConvertItem(BestItemOffer conversionItem)
        {
            if (TempData["CartHasItems"] != null)
            {
                Cart currentCart = (Cart)TempData["CurrentCart"];
                var index = currentCart.EntityList.FindIndex(x => x.ItemId == conversionItem.ItemId);

                if (index >= 0)
                    currentCart.EntityList[index].ItemId = conversionItem.BestItemId;

                TempData["CurrentCart"] = currentCart;

                var replacement = ItemDetails.GetRelacement(conversionItem.BestItemId);

                return Json(new { oldId = conversionItem.ItemId, replacement, success = true });
            }

            return Json(new { success = false });
        }

    }
}

Web3/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web3.DL;
using Web3.DOL;
using Web3.DTO;
using Web3.Helpers;
using Web3.Helpers.Filters;
using Web3.Models;

namespace Web3.Controllers
{
    public class OrderController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetOrderData(DataTableFilter dtFilter, OrderFilter filter)
        {
            var data = DTOOrder.MapToDTO(new OrderRepository().GetData(dtFilter, filter));

            return Json(new
            {
                recordsTotal = data.Count,
                recordsFiltered = data.Count,
                data = data.Data
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult PerformOrder()
        {
            try
            {
                if (TempData["CartHasItems"] != null)
                {
                    Cart currentCart = (Cart)TempData["CurrentCart"];

                    List<DTOOrderItem> orderItems = currentCart.EntityList.Select(x => new DTOOrderItem()
                    {
                        ItemId = x.ItemId,
                        Qty = x.Qty
                    }).ToList();

                    int orderId = new OrderRepository().CreateOrder();

                    List<int> subOrderIds = new SubOrderRepository().Create(orderItems, orderId);

                    List<int> orderItemIds = new OrderItemRepository().CreateOrderItems(orderItems, orderId);
                }
                else
                {
                    return Json(new { success = false, message="Cart is empty." });
                }
            }
            catch(Exception ex)
            {
                return Json(new { success = false });
            }

            TempData["CartHasItems"] = null;
            TempData["CurrentCart"] = null;
            return Json(new { success = true });
        }
    }
}

Web3/Views/Cart/Index.cshtml
@model List<Web3.DOL.ItemCategoryDetails>

<style>
    .catClass {
        background-color: #43857C;
        height: 50px;
        font-size: 24px;
        font-family: Verdana;
        font-style: italic oblique;
        color: #00352E;
        border-bottom: 2px solid black;
    }

    .itClass {
        background-color: #6BA099;
        height: 30px;
        font-size: 16px;
        font-family: Verdana;
        font-style: italic;
        color: #00352E;
        border-bottom: 1px solid black;
    }

    .itHead {
        background-color: #6BA099;
        height: 30px;
        font-size: 20px;
        font-family: Verdana;
        font-style: oblique;
        color: #00352E;
        border-bottom: 1px solid black;
    }

    .itFoot {
        background-color: #42726C;
        height: 30px;
        font-size: 20px;
        font-family: Verdana;
        font-style: oblique;
        color: #00352E;
        border-bottom: 1px solid black;
    }

    .itmQty {
        width: 120px;
        background-color: #6C7977;
    }
</style>

<h2>Cart Review</h2>

<br />
<br />
<div class="panel panel-default">

    <div class="panel-heading" data-toggle="collapse" data-target="#bottomPart">
        <h4>
            Items in cart
        </h4>
    </div>

    <div id="bottomPart" class="collapse">
        <div class="panel-body cartBody">
            @foreach (var category in Model)
            {
                var p = string.Concat(".itm", category.CategoryCode);
                var l = string.Concat("itm", category.CategoryCode);
                <div class='row catClass' data-toggle='collapse' data-target='@p' data-catid="@category.CategoryCode">
                    <div class="col-sm-8">@category.CategoryCode</div>
                    <div class="col-sm-2 catQty">@category.Qty</div>
                    <div class="col-sm-2 catPrice">@category.TotalPrice</div>
                </div>
                <div class="row itClass itHead @l">
                    <div class="col-sm-3">Item Name</div>
                    <div class="col-sm-2">Item Code</div>
                    <div class="col-sm-1">Price</div>
                    <div class="col-sm-2">Dis. Price</div>
                    <div class="col-sm-2">Quantity</div>
                    <div class="col-sm-2">Total Price</div>
                </div>
                foreach (var item in category.ItemDetails)
                {
                <div class="row itClass itInstance @l" data-id="@item.ItemId">
                    <div class="col-sm-3">@item.ItemName</div>
                    <div class="col-sm-2" data-key="itemcode">@item.ItemCode</div>
                    <div class="col-sm-1" data-key="price">@item.OneInstancePrice</div>
                    <div class="col-sm-2" data-key="discprice">@item.DiscountedPrice</div>
                    <div class="col-sm-2" data-key="qty">
                        <input class="itmQty" type="number" data-catcode="@category.CategoryCode" data-price="@item.OneInstancePrice" data-discount="@item.Discount" data-val="@item.Qty" value="@item.Qty" />
                    </div>
                    <div class="col-sm-2 rowPrice" data-key="totprice">@item.TotalPrice</div>
                </div>
                }
            }
            <div class="row itFoot pull-right">
                Total Price: <label class="totPrice">@ViewBag.TotalAmount</label>
            </div>
        </div>
    </div>

    <div class="panel-footer">
        <div class="row">
            <div class="col-sm-6"></div>
            <button class="btn btn-default col-sm-2 pull-right cartSave" style="margin-left:10px; margin-right: 10px;">Save</button>
            <button class="btn btn-default col-sm-2 pull-right cartOrder" style="margin-left:10px; margin-right: 10px;">Order</button>
            <button class="btn btn-success col-sm-2 pull-right cartAnalyze" style="margin-left:10px; margin-right: 10px;">Analyze</button>
        </div>
    </div>
</div>

<br />
<br />
<div class="panel panel-success analyzedPanel" style="display: none;">
    <div class="panel-heading">
        <h4>Best Offers</h4>
    </div>

    <div class="panel-body analyzedCart">
    </div>

    <div class="panel-footer">

    </div>
</div>

<script>
    var changeInCart = false;

    var analyzeCart = function () {
        $('.analyzedPanel').show();

        $.ajax({
            url: "@Url.Action("AnalyzeCart", "Cart")",
            type: "POST",
            success: function (result) {
                $('.analyzedCart').html(result);
                $('#analyzeTable').DataTable({
                    scrollX: true,
                });

            },
            error: function(err){
                $.notify("Error ocured during cart saving.", "error");
            }
        });
    };

    var saveCart = function (items) {
        $.ajax({
            url: "@Url.Action("SaveCart", "Cart")",
            type: "POST",
            data: {
                items
            },
            success: function (result) {
                if (result.success) {
                    $.notify("Cart is successfully saved.", "success");
                    changeInCart = false;
                }
                else {
                    $.notify("Error ocured during cart saving.", "error");
                }
            },
            error: function(err){
                $.notify("Error ocured during cart saving.", "error");
            }
        });
    }

    var performOrder = function () {
        $.ajax({
            url: "@Url.Action("PerformOrder", "Order")",
            type: "POST",
            success: function (result) {
                if (result.success) {
                    $.notify("Order is successfully performed.", "success");
                    changeInCart = false;
                    $('.cartBody').empty();
                    $('#cartNumber').text("0");
                    $('.analyzedPanel').hide();
                }
                else {
                    if (result.message != null) {
                        $.notify(message, "error");
                    }
                    else {
                        $.notify("Error ocured during order performing.", "error");
                    }
                }
            },
            error: function(err){
                $.notify("Error ocured during order performing.", "error");
            }
        });
    }

    $(document).ready(function () {
        $('#bottomPart').collapse('show');

        $(".itmQty").on('change', function () {
            debugger;
            changeInCart = true;

            var prev = $(this).data('val');
            var price = $(this).data('price');
            var discount = $(this).data('discount');
            var current = $(this).val();
            $(this).data('val', current);

            var dif = (current - prev) * (1 - discount*0.01) * price;

            var catcode = $(this).data('catcode');
            var rowPrice = Number($(this).parent().parent().find('.rowPrice').text());
            var catPrice = Number($('[data-catid="' + catcode + '"]').find('.catPrice').text());
            var catQty = Number($('[data-catid="' + catcode + '"]').find('.catQty').text());
            var totPrice = Number($('.totPrice').text());

            rowPrice = (rowPrice + dif).toFixed(4);
            catPrice = (catPrice + dif).toFixed(4);
            catQty = catQty + (current - prev);
            totPrice = (totPrice + dif).toFixed(4);

            $(this).parent().parent().find('.rowPrice').text(rowPrice);
            $('[data-catid="' + catcode + '"]').find('.catPrice').text(catPrice);
            $('[data-catid="' + catcode + '"]').find('.catQty').text(catQty);
            $('.totPrice').text(totPrice);

        });

        $(".cartSave").on('click', function () {
            var items = $('.itInstance').toArray();

            var reducedItems = items.map(function(x){
                var qty = $(x).find('.itmQty').val();
                var itemId = $(x).data('id');
                return {
                    qty,
                    itemId
                }
            });

            saveCart(reducedItems);
        });

        $(".cartOrder").on('click', function () {
            if (changeInCart) {
                $.notify("There is a change in a cart. Please save changes before order.", "error");
            }
            else {
                performOrder();
            }
        });

        $(".cartAnalyze").on('click', function () {
            analyzeCart();
        });
    });
</script>

Web3/Views/Cart/_AnalyzedCartPartial.cshtml
@model List<Web3.DOL.BestItemOffer>

<table id="analyzeTable" class="display nowrap" style="width:100%">
    <thead>
        <tr>
            <th></th>
            <td>Category Code</td>
            <td>Item Code</td>
            <td>Original Price</td>
            <td>Original Discount</td>
            <td>With Discount</td>
            <td>Original Vendor</td>
            <td>Best Item Code</td>
            <td>Best Price</td>
            <td>Best Discount</td>
            <td>Best With Discount</td>
            <td>Best Vendor</td>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            string bc;
            bool be = false;
            if (item.BestItemId == item.ItemId)
            {
                bc = "green";
                be = false;
            }
            else {
                bc = "white";
                be = true;
            }
        <tr style='background-color: @bc'>
            @if (be)
             {
            <td>
                <button class="btn btn-success" onclick="convertItem(this)" data-categoryCode="@item.CategoryCode" data-oItemId="@item.ItemId" data-bItemId="@item.BestItemId">Convert</button>
            </td>
            }
            else
            {
            <td>
            </td>
            }
            <td>@item.CategoryCode</td>
            <td>@item.ItemCode</td>
            <td>@item.OriginalPrice</td>
            <td>@item.OriginalDiscount</td>
            <td>@item.OriginalPriceWithDiscount</td>
            <td>@item.OriginalVendorName</td>
            <td>@item.BestItemCode</td>
            <td>@item.BestPrice</td>
            <td>@item.BestDiscount</td>
            <td>@item.BestPriceWithDiscount</td>
            <td>@item.BestVendorName</td>
        </tr>
        }
    </tbody>
</table>

<script>
    var convertItem = function (e) {
        var elementBtn = $(e);
        var ItemId = elementBtn.data('oitemid');
        var BestItemId = elementBtn.data('bitemid');
        var CategoryCode = elementBtn.data('categorycode');  

        $.ajax({
            url: "@Url.Action("ConvertItem", "Cart")",
            type: "POST",
            data: {
                ItemId, BestItemId, CategoryCode 
            },
            success: function (result) {
                if (result.success) {
                    changeInCart = true;
                    var element = $('[data-id="' + result.oldId + '"]');

                    var itemCode = element.find('[data-key=itemcode]');
                    var price = element.find('[data-key=price]');
                    var discprice = element.find('[data-key=discprice]');
                    var qty = element.find('[data-key=qty]');
                    var qtyInput = qty.find('.itmQty');

                    var rowTotPrice = element.find('[data-key=totprice]');
                    var catTotPrice = $('[data-catid="' + result.replacement.CategoryCode + '"]').find('.catPrice');
                    var totPrice = $('.totPrice');

                    var qtyValue = Number(qtyInput.val());
                    var discPriceValue = Number(discprice.text());
                    var newDiscPriceValue = result.replacement.DiscountedPrice;
                    var rowPriceOld = Number(rowTotPrice.text());
                    var catPriceOld = Number(catTotPrice.text());
                    var totPriceOld = Number(totPrice.text());

                    var priceDelta = qtyValue * (newDiscPriceValue - discPriceValue);
                    var totPriceNew = totPriceOld + priceDelta;
                    var catPriceNew = catPriceOld + priceDelta;
                    var rowPriceNew = rowPriceOld + priceDelta;

                    totPrice.text(totPriceNew.toFixed(4));
                    catTotPrice.text(catPriceNew.toFixed(4));
                    rowTotPrice.text(rowPriceNew.toFixed(4));

                    itemCode.text(result.replacement.ItemCode);
                    price.text(result.replacement.OneInstancePrice);
                    discprice.text(result.replacement.DiscountedPrice);
                    qtyInput.data('price', result.replacement.OneInstancePrice);
                    qtyInput.data('discount', result.replacement.Discount);

                    element.data('id', result.replacement.ItemId);

                    elementBtn.parent().parent().css('background-color', 'green');
                    elementBtn.remove();
                }
                else {
                    $.notify("Error ocured during conversion performing.", "error");
                }
            },
            error: function(err){
                $.notify("Error ocured during conversion performing.", "error");
            }
        });
    }
</script>